<a href="https://colab.research.google.com/github/akansha1220/python/blob/master/Hyperparameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##All Hyperparameter Tunning
1. GridsearchCV
2. RandomizedSearchedCV
3. Bayesian Optimization- Automatr Hyperparameter tuning(Hyperopt)
4. Sequential MOdelBased Optimization(Tuning a scikit-learn estimator with Huperopt)
5. Optuna- Automate Hyperparameter Tuning
6. Genetic Algoritms(TPOT CLassifier)


In [1]:
from sklearn.ensemble import RandomForestClassifier

In [2]:
rf = RandomForestClassifier()

In [3]:

import warnings
warnings.filterwarnings('ignore')

In [7]:
import pandas as pd
df = pd.read_csv('/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
import numpy as np
df['Glucose'] = np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35        0  33.6   
1            1     85.0             66             29        0  26.6   
2            8    183.0             64              0        0  23.3   
3            1     89.0             66             23       94  28.1   
4            0    137.0             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
df['Insulin'] = np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35     30.5  33.6   
1            1     85.0             66             29     30.5  26.6   
2            8    183.0             64              0     30.5  23.3   
3            1     89.0             66             23     94.0  28.1   
4            0    137.0             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
df['SkinThickness'] = np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
#depenedent and independent features

X=df.drop('Outcome',axis=1)
y = df['Outcome']

In [12]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72           35.0     30.5  33.6   
1              1     85.0             66           29.0     30.5  26.6   
2              8    183.0             64           23.0     30.5  23.3   
3              1     89.0             66           23.0     94.0  28.1   
4              0    137.0             40           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0             76           48.0    180.0  32.9   
764            2    122.0             70           27.0     30.5  36.8   
765            5    121.0             72           23.0    112.0  26.2   
766            1    126.0             60           23.0     30.5  30.1   
767            1     93.0             70           31.0     30.5  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [13]:

y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,random_state=33,test_size=0.20)

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=10).fit(X_train,Y_train)
prediction = rf_classifier.predict(X_test)

In [16]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [17]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,prediction))
print(classification_report(Y_test,prediction))
print(accuracy_score(Y_test,prediction))

[[83 16]
 [24 31]]
              precision    recall  f1-score   support

           0       0.78      0.84      0.81        99
           1       0.66      0.56      0.61        55

    accuracy                           0.74       154
   macro avg       0.72      0.70      0.71       154
weighted avg       0.73      0.74      0.74       154

0.7402597402597403


In [18]:
#Manual Hyperparameter Tuning
model = RandomForestClassifier(n_estimators=300,criterion='entropy',max_features='sqrt',
                               min_samples_leaf=10,random_state=100)
model = model.fit(X_train,Y_train)
prediction = model.predict(X_test)
print(confusion_matrix(Y_test,prediction))
print(classification_report(Y_test,prediction))
print(accuracy_score(Y_test,prediction))

[[87 12]
 [28 27]]
              precision    recall  f1-score   support

           0       0.76      0.88      0.81        99
           1       0.69      0.49      0.57        55

    accuracy                           0.74       154
   macro avg       0.72      0.68      0.69       154
weighted avg       0.73      0.74      0.73       154

0.7402597402597403


#Randomized Search CV



*   Narrow down the the result
*   List item



In [20]:
from sklearn.model_selection import RandomizedSearchCV
#Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200 ,stop= 2000, num = 10)]
#Number of features is consider to split
max_features = ['auto','sqrt','log2']
#Maximum number of level in tree
max_depth = [int(x) for x in np.linspace(10,1000,10)]
#Number of samples required at each leaf node
min_samples_leaf = [1,2,4,6,8]
#Number of samples required to split a node
min_samples_split = [2,5,10,14]
#creating a random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth' : max_depth,
               'min_samples_leaf' : min_samples_leaf,
               'min_samples_split' : min_samples_split,
               'criterion':['entropy','gini']}

print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_leaf': [1, 2, 4, 6, 8], 'min_samples_split': [2, 5, 10, 14], 'criterion': ['entropy', 'gini']}


In [23]:

rf = RandomForestClassifier()
rf_randomcv = RandomizedSearchCV(estimator=rf,param_distributions = random_grid,n_iter=100,
                                    cv=3,verbose=2,random_state = 100, n_jobs=-1)
rf_randomcv.fit(X_train,Y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [24]:
# best parameter /area where 

rf_randomcv.best_params_

{'n_estimators': 1400,
 'min_samples_split': 14,
 'min_samples_leaf': 2,
 'max_features': 'auto',
 'max_depth': 780,
 'criterion': 'gini'}

In [25]:
rf_randomcv

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [27]:
best_random_grid = rf_randomcv.best_estimator_

In [29]:
y_pred = best_random_grid.predict(X_test)

print(confusion_matrix(Y_test,y_pred))
print("Classification report {}".format(classification_report(Y_test,y_pred)))
print("Accuracy Score {}".format(accuracy_score(Y_test,y_pred)))

[[86 13]
 [24 31]]
Classification report               precision    recall  f1-score   support

           0       0.78      0.87      0.82        99
           1       0.70      0.56      0.63        55

    accuracy                           0.76       154
   macro avg       0.74      0.72      0.72       154
weighted avg       0.75      0.76      0.75       154

Accuracy Score 0.7597402597402597


In [32]:
from sklearn.model_selection import GridSearchCV

param_grid = {
      'criterion':[rf_randomcv.best_params_['criterion']],
      'max_depth':[rf_randomcv.best_params_['max_depth']],
      'max_features':[rf_randomcv.best_params_['max_features']],
      'min_samples_leaf':[rf_randomcv.best_params_['min_samples_leaf'],
                          rf_randomcv.best_params_['min_samples_leaf']+2,
                          rf_randomcv.best_params_['min_samples_leaf']+4],
      'min_samples_split':[rf_randomcv.best_params_['min_samples_split']-2,
                          rf_randomcv.best_params_['min_samples_split']-1,
                          rf_randomcv.best_params_['min_samples_split'],
                           rf_randomcv.best_params_['min_samples_split']+1,
                          rf_randomcv.best_params_['min_samples_split']+2],
      'n_estimators' :[rf_randomcv.best_params_['n_estimators']-200,
                          rf_randomcv.best_params_['n_estimators']-100,
                          rf_randomcv.best_params_['n_estimators'],
                           rf_randomcv.best_params_['n_estimators']+100,
                          rf_randomcv.best_params_['n_estimators']+200]}

print(param_grid)

{'criterion': ['gini'], 'max_depth': [780], 'max_features': ['auto'], 'min_samples_leaf': [2, 4, 6], 'min_samples_split': [12, 13, 14, 15, 16], 'n_estimators': [1200, 1300, 1400, 1500, 1600]}


In [33]:
rf_randomcv.best_params_['criterion']

'gini'

In [34]:
rf_randomcv.best_params_['max_depth']

780

In [35]:
rf_randomcv.best_params_['max_features']

'auto'

In [36]:
## Fit the grid_search to the data
rf = RandomForestClassifier()
grid_search = GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=True)
grid_search.fit(X_train,Y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [780],
                         'max_features': ['auto'],
                         'min_samples_leaf': [2, 4, 6],
                         'min_samples_split': [12, 13, 14, 15, 16],
                         'n_estimators': [1200, 1300, 1400, 1500, 1600]},
             verbose=True)

In [37]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=780, max_features='auto', min_samples_leaf=6,
                       min_samples_split=16, n_estimators=1600)

In [40]:
best_grid = grid_search.best_estimator_


In [41]:
best_grid

RandomForestClassifier(max_depth=780, max_features='auto', min_samples_leaf=6,
                       min_samples_split=16, n_estimators=1600)

In [42]:
y_pred = best_grid.predict(X_test)

print(confusion_matrix(Y_test,y_pred))
print("Classification report {}".format(classification_report(Y_test,y_pred)))
print("Accuracy Score {}".format(accuracy_score(Y_test,y_pred)))

[[88 11]
 [26 29]]
Classification report               precision    recall  f1-score   support

           0       0.77      0.89      0.83        99
           1       0.72      0.53      0.61        55

    accuracy                           0.76       154
   macro avg       0.75      0.71      0.72       154
weighted avg       0.76      0.76      0.75       154

Accuracy Score 0.7597402597402597


#Automated Hyperparameter tunning

Automated Hyperparameter Tuning can be done by using techniques such as

* Bayesian Optimization
* Gradient Descent
* Evolutionary Algorithm

**Bayesian Optimization**

Bayesian OPtimization uses probability to find the minimum of a function.The Final aim is find the input to a function which can give us the lowest possible output value. It usually perform better than random grid and manual search providing better performance in the testing phase and reduced the optimization time.In Hyperopt,Bayesian Optimization time. In Hyperopt, Bayesian optimization can be implemented giving 3 three main parameters to the function fmin.

* objective Function = defines the loss function to minimize.
* Domain Space = defines the range of input values to test(in Bayesian optimization this space creates a probability distribution for each of the uses Hyperparameter).
* Optimization Algorithm = defines the search algorithm to use to select the best the best input value use in each new iteration

In [43]:
##pip install hyperopt
pip install hyperopt

SyntaxError: ignored

In [46]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [51]:
space = {'criterion':hp.choice('criterion',['entropy','gini']),
         'max_depth': hp.quniform('max_depth',10,1200,10),
         'max_features': hp.choice('max_features',['auto','sqrt','log2',None]),
         'min_samples_leaf': hp.uniform('min_samples_leaf',0,0.5),
         "min_samples_split": hp.uniform('min_samples_split',0,1),
         'n_estimators': hp.choice('n_estimators',[10,50,300,750,1200,1300])}

In [55]:
space['criterion']

In [62]:
def objective(space):
  model = RandomForestClassifier(criterion = space['criterion'],max_depth=space['max_depth'],
                                 min_samples_leaf=space['min_samples_leaf'],min_samples_split=space['min_samples_split'],
                                 n_estimators = space['n_estimators'])
  
  accuracy = cross_val_score(model,X_train,Y_train,cv=5).mean()

  return {'loss':-accuracy,'status':STATUS_OK}

In [64]:
from sklearn.model_selection import cross_val_score

trials = Trials()
best = fmin(fn = objective,space = space,algo=tpe.suggest,max_evals =80,trails = trails)

best

NameError: ignored