In [63]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [36]:
steps = [("Scaling",StandardScaler()),
        ("Model",LogisticRegression())]

In [37]:
steps


[('Scaling', StandardScaler()), ('Model', LogisticRegression())]

In [38]:
pipe = Pipeline(steps)

In [10]:
#visvalzation of pipelne
from sklearn import set_config


In [11]:
set_config(display="diagram")

In [12]:
pipe

Pipeline(steps=[('Scaling', StandardScaler()), ('Model', LinearRegression())])

In [15]:
#Create a dataset
from sklearn.datasets import make_classification

In [25]:
X,y = make_classification(n_samples=1000)

In [26]:
X.shape

(1000, 20)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [30]:
X_train

array([[-0.87956107,  0.13033913, -1.27854748, ..., -0.40466938,
        -1.56508395, -0.24486275],
       [-0.09313566, -0.74587505,  0.96398677, ..., -0.4069339 ,
        -0.67556329, -1.99798142],
       [ 1.39969725, -1.27834033, -0.97902309, ..., -1.55560071,
         1.8135667 , -1.88847297],
       ...,
       [-0.35184229,  1.56735223, -0.40500399, ..., -1.50016486,
        -0.67563577, -1.21033678],
       [ 1.12956023, -0.07889329, -0.52210619, ...,  1.00285702,
         0.97997187, -1.07165782],
       [-0.17243074, -0.16285206,  0.61110035, ..., -0.17584971,
         2.09517922,  1.41353643]])

In [39]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('Scaling', StandardScaler()), ('Model', LogisticRegression())])

In [40]:
y_pred = pipe.predict(X_test)

In [41]:
y_pred

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,

In [43]:
#second Exaple
#Displaying a pipeline with standard scaler,dimensnionally reduction and the estimator

In [60]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [61]:
steps = [("Scaling",StandardScaler()),
        ("PCA",PCA(n_components=3)),
        ("SVC",SVC())]

In [62]:
pipeline = Pipeline(steps)

TypeError: 'Pipeline' object is not callable

In [49]:
Pipeline

Pipeline(steps=[('Scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [50]:
Pipeline['Scaling'].fit_transform(X_train)

array([[-0.83201469,  0.10966268, -1.24664249, ..., -0.4436434 ,
        -1.60318445, -0.19158273],
       [-0.06244626, -0.79915563,  0.92432554, ..., -0.44596929,
        -0.68147411, -1.63352591],
       [ 1.39838787, -1.35143406, -0.95667685, ..., -1.625765  ,
         1.89773167, -1.54345502],
       ...,
       [-0.31560753,  1.60014735, -0.40097648, ..., -1.56882684,
        -0.68154921, -0.98568681],
       [ 1.13404123, -0.10735533, -0.51434158, ...,  1.00202701,
         1.03397099, -0.87162313],
       [-0.14004166, -0.19443823,  0.58270081, ..., -0.20862271,
         2.18953509,  1.17245351]])

In [58]:
pipeline.fit(X_train,Y_train)

NameError: name 'pipeline' is not defined

In [52]:
Pipeline.predict(X_test)

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,

# complex examples of columns transformer

In [64]:
from sklearn.impute import SimpleImputer
import numpy as np

In [65]:
#numerical data
numeric_processor = Pipeline(
    steps = [("imputation",SimpleImputer(missing_values=np.nan,strategy='mean')),
            ("Scaler",StandardScaler())]
)

In [67]:
#numerical data

from sklearn.preprocessing import OneHotEncoder
categoric_processor = Pipeline(
    steps = [("imputation",SimpleImputer(fill_value="missing",strategy='constant')),
            ("Onehot",OneHotEncoder(handle_unknown = "ignore"))]
)

In [68]:
categoric_processor

Pipeline(steps=[('imputation',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('Onehot', OneHotEncoder(handle_unknown='ignore'))])

In [69]:
from sklearn.compose import ColumnTransformer

In [71]:
preprocessor = ColumnTransformer(
[("categorical",categoric_processor,['gender','city']),
("numerical",numeric_processor,['age','height'])])

In [72]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('Onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer()),
                                                 ('Scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [74]:
from sklearn.pipeline import make_pipeline

In [75]:
pipe = make_pipeline(preprocessor,LogisticRegression())

In [76]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('Onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation',
                                                                   SimpleImputer()),
                                                                  ('Scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])

In [ ]:
P